name: SimpleRestarter
version: ${project.version}
main: indi.lkidszzzz.simplerestarter.SimpleRestarter
api-version: 1.13
author: lkidszzzz
description: Restart your minecraft server simply and automatically.